name: 'dwh_demo'
version: '1.0.0'
config-version: 2


profile: 'dwh_demo'

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dwh_demo:
    staging:
      +materialized: view
      +schema: stg
